Repository GetDKAN/dkan, pull requests merged in 2018-04, with the labels that each got.

#2458 Fix the chrome issue
  .circleci/config.yml
  test/features/workflow.feature
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
Labels: in progress

#2456 Remove exra docker dir
  .docker/CHANGELOG.md
  .docker/README.md
  .docker/VERSION
  .docker/bin/docker-bash
  .docker/bin/docker-drush
  .docker/bin/dsh
  .docker/docs/behat.md
  .docker/docs/db-sandbox.md
  .docker/docs/drupal-settings.md
  .docker/docs/img/unionfs-container.png
  .docker/docs/img/unionfs-your-image.png
  .docker/docs/multiple-projects.md
  .docker/docs/public-access.md
  .docker/docs/settings.md
  .docker/etc/mysql/my.cnf
  .docker/etc/php5/php-cli.ini
  .docker/etc/php5/php.ini
  .docker/etc/solr/3.x/elevate.xml
  .docker/etc/solr/3.x/mapping-ISOLatin1Accent.txt
  .docker/etc/solr/3.x/protwords.txt
  .docker/etc/solr/3.x/schema.xml
  .docker/etc/solr/3.x/schema_extra_fields.xml
  .docker/etc/solr/3.x/schema_extra_types.xml
  .docker/etc/solr/3.x/solrconfig.xml
  .docker/etc/solr/3.x/solrconfig_extra.xml
  .docker/etc/solr/3.x/solrcore.properties
  .docker/etc/solr/3.x/stopwords.txt
  .docker/etc/solr/3.x/synonyms.txt
Labels: in progress

#2466 Updates the changelog in preparation for 1.14.6.
  CHANGELOG.txt
Labels: in progress

#2464 Move functions out of .install
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.install
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.module
Labels: code review

#2467 Command center menu update
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.features.menu_links.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.info
  test/features/user.site_manager.feature
Labels: code review

#2434 Disable option to assign content to anon
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_user/dkan_sitewide_user.module
Labels: in progress

#2427 Adjust tests to work given client config
  test/features/dataset.all.feature
  test/features/dataset.author.feature
  test/features/home.feature
  test/features/panels.feature
  test/features/topics.feature
  test/features/workflow.feature
Labels: code review

#2405 Adjust group.editor.feature so we only create content when needed
  test/features/group.editor.feature
Labels: B3, code review
