Repository GetDKAN/dkan, pull requests merged in 2018-07, with the labels that each got.

#2587 Restore circleci behat testing
  .circleci/config.yml
Labels: In Progress

#2557 Wrap Dkan defined string to improve multilingual support
  modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc
  modules/dkan/dkan_sitewide/dkan_sitewide.module
Labels: Code Review

#2588 More granular field validation for datasets and resources.
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
Labels: Code Review

#2589 Update uuid to 1.1
  drupal-org.make
Labels: Code Review

#2592 Update css for ppt/pptx files
  modules/dkan/dkan_dataset/css/dkan_dataset.css
Labels: Code Review

#2600 Updating workflow.rst to fix bad spelling/writing
  docs/components/workflow.rst
Labels: In Progress

#2534 Add iframe instructions to documentation
  docs/components/storytelling.rst
Labels: Internal QA

#2586 Change remote file url handling when harvesting
  docs/components/harvest.rst
  modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
  test/phpunit/boot.php
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
  test/phpunit/phpunit_redirect_test.php
Labels: Code Review

#2606 Final Workflow content improvements
  docs/components/workflow.rst
Labels: In Progress

#2607 Restore working harvest tests
  test/phpunit/dkan_dataset/DataJsonTest.php
  test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
  test/phpunit/dkan_harvest/DkanHarvestTest.php
  test/phpunit/phpunit.xml
Labels: In Progress

#2418 Updating Add Content page and content types
  docs/admin/data_and_content/adding_new_content.rst
Labels: To Do
