Repository GetDKAN/dkan, pull requests merged in 2018-11, with the labels that each got.

#2723 Include dkan.profile to prevent undefined function in update
  dkan.install
Labels: 1.16, Code Review

#2718 Update odsm_dkan token values
  modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
Labels: In Progress

#2724 Update contrib modules
  drupal-org.make
Labels: 1.16, In Progress

#2721 Update dkan-sites.rst
  docs/introduction/dkan-sites.rst
Labels: Upcoming sprint

#2725 Update dkan-sites.rst.
  docs/introduction/dkan-sites.rst
Labels: In Progress

#2713 Allowing the CSV parser to handle trailing delimiters in records and …
  modules/dkan/dkan_datastore/README.md
  modules/dkan/dkan_datastore/dkan_datastore.module
  modules/dkan/dkan_datastore/dkan_datastore.pages.inc
  modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
  modules/dkan/dkan_datastore/modules/dkan_datastore_simple_import/src/SimpleImport.php
  modules/dkan/dkan_datastore/src/CsvParser.php
  modules/dkan/dkan_datastore/src/LockableDrupalVariables.php
  modules/dkan/dkan_datastore/src/Manager/Manager.php
  modules/dkan/dkan_datastore/src/Manager/ManagerInterface.php
  modules/dkan/dkan_datastore/src/Page/Component/ManagerConfiguration.php
  modules/dkan/dkan_datastore/src/Page/Component/Status.php
  modules/dkan/dkan_datastore/src/Page/Page.php
  modules/dkan/dkan_datastore/src/Parser/Base.php
  modules/dkan/dkan_datastore/src/Parser/Csv.php
  modules/dkan/dkan_datastore/src/Parser/CsvBase.php
  modules/dkan/dkan_datastore/src/Parser/Field.php
  modules/dkan/dkan_datastore/src/Parser/QuotedField.php
  modules/dkan/dkan_datastore/src/StateMachine.php
  test/features/resource.admin.feature
  test/features/resource.author.feature
  test/features/resource.editor.feature
  test/phpunit/dkan_datastore/DkanDatastoreCsvParserTest.php
  test/phpunit/dkan_datastore/DkanDatastoreTest.php
Labels: Code Review

#2740 Revision fix
  modules/dkan/dkan_workflow/dkan_workflow.module
Labels: In Progress

#2751 Add issue_template.md to .github dir
  .github/ISSUE_TEMPLATE.md
Labels: Code Review

#2752 Temp doc adjustment until API is fixed
  docs/apis/datastore-api.rst
Labels: Code Review

#2722 Update rest-api.rst
  docs/apis/rest-api.rst
Labels: Code Review

#2690 Number of Datasets and Topics Recipe
  docs/development/display-num-datasets.rst
  docs/development/index.rst
Labels: 1.16, Code Review
