Repository GetDKAN/dkan, pull requests merged in 2018-03, with the labels that each got.

#2407 2340-data-dictionaries-b
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.module
  modules/dkan/dkan_data_dictionary/js/dkan_data_dictionary.js
Labels: USDA, code review

#2412 Installation instructions for ahoy
  docs/index.rst
  docs/installation/basic.rst
  docs/installation/index.rst
  docs/installation/local-dev.rst
  docs/introduction/get-dkan.md
  docs/introduction/index.rst
Labels: in progress

#2409 Allows the services API to be able to consume datasets with the same…
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
  test/composer.json
  test/composer.lock
  test/dkanextension/src/Drupal/DKANExtension/Context/ServicesContext.php
  test/features/data_story.author.feature
  test/features/dataset.admin.feature
  test/features/dataset_rest_api.feature
  test/features/datastore.feature
  test/features/theme.admin.feature
  test/phpunit/dkan_dataset/ApiTest.php
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
  test/phpunit/phpunit.xml
Labels: in progress

#2411 Dataset collections et
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.features.field_base.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.features.field_instance.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.install
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.module
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.views_default.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.field_group.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
  test/features/dataset.collections.feature
Labels: USDA, in progress

#2435 Upgrade drupal to 7.58
  CHANGELOG.txt
  drupal-org-core.make
Labels: in progress
