Repository GetDKAN/dkan, pull requests merged in 2018-05, with the labels that each got.

#2489 Allows the user to change the map-tiles url used for the 'Data Extent…
  docs/components/dataset/datasetfeatures.rst
  modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
Labels: in progress

#2476 Update getExtension() and createResources() functions
  modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
  modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
Labels: Release

#2463 Update Circle Setup to Use Local Dev Containers
  .ahoy/.scripts/circle-behat.rb
  .ahoy/docker.ahoy.yml
  .circleci/config.yml
  .circleci/tests/circle/circle.conf
  CHANGELOG.txt
  modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_voting/dkan_dataset_voting.info
  modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.info
  modules/dkan/dkan_datastore/modules/dkan_datastore_fast_import/dkan_datastore_fast_import.info
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panelizer/dkan_sitewide_panelizer.info
  modules/dkan/dkan_topics/modules/dkan_default_topics/dkan_default_topics.info
  test/assets/README.md
  test/composer.json
  test/composer.lock
  test/features/dataset.admin.feature
  test/features/datastore_fast_import.feature
  test/features/dkan_harvest.feature
  test/features/group.admin.feature
  test/features/recline.feature
  test/features/resource.author.feature
  test/features/resource.editor.feature
  test/phpunit/dkan_dataset/DataJsonTest.php
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
  test/phpunit/dkan_datastore_fast_import/DkanDatastoreFastImportTest.php
  themes/nuboot_radix/nuboot_radix.info
Labels: Epic: Our containers in CircleCI, in progress

#2498 Fix the link to installation info on README
  README.md
Labels: code review

#2521 Apply custom validation rules to REST API node creation
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.api.php
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
  modules/dkan/dkan_dataset/tests/dkan_dataset_test.info
  modules/dkan/dkan_dataset/tests/dkan_dataset_test.module
  test/phpunit/dkan_dataset/ApiTest.php
Labels: code review

#2527 Stop xdebug in web and cli for tests
  .circleci/config.yml
Labels: code review

#2526 Change default harvest source modified date to blank
  dkan.install
  modules/dkan/dkan_dataset/dkan_dataset.install
  modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.features.field_instance.inc
  test/features/resource.editor.feature
Labels: in progress
