Repository GetDKAN/dkan, pull requests merged in 2018-06, with the labels that each got.

#2542 Add option to adjust height of the hero region
  themes/nuboot_radix/includes/panel.inc
  themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php
  themes/nuboot_radix/theme-settings.php
Labels: code review

#2562 Fixing the url we are getting docker from for CircleCI.
  .circleci/config.yml
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
Labels: in progress

#2563 Remove changelog checkbox from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#2552 Run linting before tests
  .circleci/config.yml
Labels: code review

#2553 Add an example on how to set the dkan_map_tile_url variable
  docs/components/dataset/datasetfeatures.rst
Labels: code review

#2561 Test improvements
  test/features/dataset.all.feature
  test/features/search.feature
Labels: code review

#2519 Control datastore via REST API
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.services.inc
  modules/dkan/dkan_datastore/dkan_datastore.info
  modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.info
  modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
  modules/dkan/dkan_datastore/modules/dkan_datastore_fast_import/dkan_datastore_fast_import.module
  modules/dkan/dkan_datastore/modules/dkan_datastore_simple_import/dkan_datastore_simple_import.info
  modules/dkan/dkan_datastore/modules/dkan_datastore_simple_import/dkan_datastore_simple_import.module
  modules/dkan/dkan_datastore/resources/dkan_datastore_resource.inc
  modules/dkan/dkan_datastore/src/Pages.php
  test/features/datastore.feature
  test/phpunit/boot.php
  test/phpunit/dkan_datastore_api/DkanDatastoreAPITest.php
Labels: Code Review, Epic: Datastore control with API

#2576 Add redirect to search page on 404 status
  modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
  modules/dkan/dkan_sitewide/dkan_sitewide.module
  test/features/search.feature
Labels: In Progress
