Repository GetDKAN/dkan, pull requests merged in 2018-02, with the labels that each got.

#2370 Patch features to add new line after <?php
  drupal-org.make
Labels: code review

#2341 Modifies curl settings so url headers and info can be properly acquired with curl
  modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
Labels: code review

#2359 Upgrade filefield_sources to 1.11
  drupal-org.make
Labels: code review

#2371 Changelog for the 1.14.2 patch release.
  CHANGELOG.txt
Labels: in progress

#2369 Add resource-level data dictionaries with JSON schema
  dkan.info
  drupal-org.make
  modules/dkan/dkan_data_dictionary/css/dkan_data_dictionary.css
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.features.field_base.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.features.field_instance.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.features.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.field_group.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.info
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.module
  modules/dkan/dkan_data_dictionary/js/editor.js
  test/dkanextension/src/Drupal/DKANExtension/Context/ResourceContext.php
  test/features/resource.author.feature
Labels: Epic: Data Dictionaries, USDA, code review, in progress

#2376 Dictionaries filefield
  modules/dkan/dkan_data_dictionary/css/dkan_data_dictionary.css
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.features.field_base.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.features.field_instance.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.field_group.inc
  modules/dkan/dkan_data_dictionary/dkan_data_dictionary.info
  modules/dkan/dkan_data_dictionary/js/editor.js
  test/dkanextension/src/Drupal/DKANExtension/Context/ResourceContext.php
  test/features/resource.author.feature
Labels: Epic: Data Dictionaries, USDA, code review, in progress

#2377 Security update for Entity API
  drupal-org.make
Labels: in progress

#2351 Dataset collections - initial build-out
  dkan.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.features.field_base.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.features.field_instance.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.features.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.module
  modules/dkan/dkan_dataset/modules/dkan_dataset_collections/dkan_dataset_collections.views_default.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.facetapi_defaults.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.features.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.info
  test/features/dataset.collections.feature
Labels: USDA, enhancement, in progress

#2378 Integration 1.14.3
  CHANGELOG.txt
  OWNERS.md
  docs/_static/css/custom.css
  docs/admin/index.rst
  docs/admin/sitemanagermaintenance
  docs/community/help.rst
  docs/conf.py
  docs/requirements.txt
  drupal-org.make
  modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
  modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
  modules/dkan/dkan_sitewide/dkan_sitewide.views_default.inc
  test/features/resource.all.feature
  test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
Labels: in progress

#2375 Simplify background content on tests
  test/behat.yml
  test/dkanextension/src/Drupal/DKANExtension/Context/DKANContext.php
  test/features/dataset.all.feature
  test/features/datastore.feature
  test/features/group.admin.feature
  test/features/group.author.feature
  test/features/group.editor.feature
  test/features/leaflet_draw_widget.feature
  test/features/theme.admin.feature
  test/features/user.admin.feature
  test/features/user.all.feature
  test/features/user.site_manager.feature
Labels: code review

#2402 Update Drupal core to 7.57
  drupal-org-core.make
Labels: in progress

#2404 Check var is set
  themes/nuboot_radix/includes/panel.inc
Labels: in progress

#2410 Integration 1.14.4
  CHANGELOG.txt
  drupal-org-core.make
  test/behat.yml
  test/dkanextension/src/Drupal/DKANExtension/Context/DKANContext.php
  test/features/dataset.all.feature
  test/features/datastore.feature
  test/features/group.admin.feature
  test/features/group.author.feature
  test/features/group.editor.feature
  test/features/leaflet_draw_widget.feature
  test/features/theme.admin.feature
  test/features/user.admin.feature
  test/features/user.all.feature
  test/features/user.site_manager.feature
  themes/nuboot_radix/includes/panel.inc
Labels: in progress
