Repository GetDKAN/dkan, pull requests merged in 2019-01, with the labels that each got.

#2785 Support harvest dataset source identifiers that ends with a '/'
  modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
Labels: Code Review

#2784 Update Harvest node machine name field settings to limit length and replace single hypen
  modules/dkan/dkan_harvest/dkan_harvest.features.field_base.inc
Labels: In Progress

#2788 Upgrade contrib modules to latest versions
  drupal-org.make
Labels: Code Review

#2787 Adding boolean disclaimer
  docs/apis/rest-api.rst
Labels: Internal QA

#2778 Add check for partial date elements when validating
  modules/dkan/dkan_dataset/dkan_dataset.module
Labels: In Progress

#2793 Fixed description of aggregation functions min and max in docs.
  docs/apis/datastore-api.rst
Labels: Code Review

#2800 Update Drupal Core to 7.62
  drupal-org-core.make
Labels: In Progress

#2805 Upgrade drupal to 7.63
  drupal-org-core.make
Labels: Code Review
