Repository GetDKAN/dkan, pull requests merged in 2020-01, with the labels that each got.

#2985 Remove deprecated dkan roles perms module
  dkan.install
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.og_features_permission.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.user_permission.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.user_role.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.info
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.install
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.module
Labels: 1.18

#2733 Decouple search from panels, other features
  dkan.info
  dkan.install
  dkan.profile
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.facetapi_defaults.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.features.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.info
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.module
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.pages_default.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.security.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.strongarm.inc
  modules/dkan/dkan_dataset/modules/dkan_dataset_search/dkan_dataset_search.views_default.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.path_breadcrumbs.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.features.inc
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.info
  modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.module
Labels: 1.17, USDA, WIP

#3002 Add release script and Jenkinsfile
  Jenkinsfile
  scripts/release-upload-assets.php
Labels: devops
